name: 🐞 Bug Report
description: File a new bug report for AxonOps Workbench for Apache Cassandra®
title: '[bug]: '
labels: [Bug, Needs Triage]
body:
  - type: markdown
    attributes:
      value: ':stop_sign: _AxonOps Workbench for Cassandra is currently in beta for its very first release. Please ensure you have the latest build before raising a bug. For support questions, please visit the project discussions forumn [https://github.com/axonops/axonops-workbench-cassandra/discussions](https://github.com/axonops/axonops-workbench-cassandra/discussions) instead._'
  - type: checkboxes
    attributes:
      label: 'Do I have the most recent version of AxonOps Workbench installed?'
      description: 'Workbench is currently in beta with versions being recently released. Before raising a bug please check you are on the latest release. [https://github.com/axonops/axonops-workbench-cassandra/releases](https://github.com/axonops/axonops-workbench-cassandra/releases) '
      options:
      - label: 'I am using the most recent beta release'
        required: true
