blank_issues_enabled: false
contact_links:
  - name: ❓ Questions & non-issue related topics
    url: https://github.com/axonops/axonops-workbench-cassandra/discussions
    about: Please use the AxonOps Workbench Discussions forum for questions an non-issue related topics.